{
 "title": "Stock Prediction",
 "time": { "from": "2022-01-17T20:06:18.416Z", "to": "2022-02-02T23:06:36.909Z" },
 "panels": [
  {
   "title": "Process Cpu",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  {
   "title": "Request Seconds Bucket",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_highr_seconds_bucket{instance=\"host.docker.internal:8181\",job=\"app\",le=\"0.75\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Process Start",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds{instance=\"host.docker.internal:8181\",job=\"app\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_size_bytes_count{handler=\"/\",instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  {
   "title": "Response Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_count{handler=\"/metrics\",instance=\"host.docker.internal:8181\",job=\"app\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Request Models",
   "type": "graph",
   "gridPos": { "h": 13, "w": 5, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/models\",instance=\"host.docker.internal:8181\",job=\"app\",method=\"POST\",status=\"2xx\"}"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{handler=~\"/docs|/listmodels|/metrics\",instance=\"host.docker.internal:8181\",job=\"app\",method=\"GET\",status=\"2xx\"}"
    }
   ]
  },
  {
   "title": "Second Bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{handler=\"/docs\",instance=\"host.docker.internal:8181\",job=\"app\",le=\"0.5\"}"
    }
   ]
  },
  {
   "title": "Garbage Collector Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{generation=~\"0|1|2\",instance=\"host.docker.internal:8181\",job=\"app\"}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 29 } }
 ]
}