apiVersion: v1
kind: Service
metadata:
  name: stockprediction-service
spec:
  selector:
    app: stockprediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8181
  type: LoadBalancer
  # externalIPs:
  # - 192.168.0.10


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockprediction-deploy
  labels:
    app: stockprediction-app
    test: test
spec:
  selector:
    matchLabels:
      app: stockprediction-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stockprediction-app
    spec:
      containers:
      - name: stockprediction-app
        image: suriyaprakashsah/stockpredictfastapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8181
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
